# -*- coding: utf-8 -*-
"""Dictionary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10STWtkGktsZJlfqhyThehYnaMJ9cg5KE

Write a Python program that allows the user
to create a dictionary of personal details for
a group of people. The program should ask
the user to enter the name, age, and
occupation for each person, and then store
this information in a dictionary. Once all the
details have been entered, the program
should print out the dictionary
"""

n = int(input("Enter how many names you want to enter: "))
# initialize empty dictionary
person_details=[]
for i in range(n):
  user_name=input("Enter name : ")
  user_age=input("Enter age: ")
  user_occupation =input("enter occupiation:")

  person = {"name":user_name, "age":user_age,"occupiation":user_occupation}
  person_details.append(person)
print(person_details)

