# -*- coding: utf-8 -*-
"""Python game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GnK8cyfnz2ktCmvaQdGVL21ONsVjv4T4

**Rock, scissor paper game**
"""

import random
user = input("Enter a choice : (rock, paper, scissors)\n")
possible_action = ["rock", "paper","scissors"]
computer_action = random.choice(possible_action)
print(f"\nYou chose {user}, computer chose {computer_action}.\n")
if user == computer_action:
    print(f"Both players selected {user}. It's a tie! again chose")
elif user == "rock":
    if computer_action == "scissors":
        print("Rock smashes scissors! You win!")
    else:
        print("Paper covers rock! You lose.")
elif user == "paper":
    if computer_action == "rock":
        print("Paper covers rock! You win!")
    else:
        print("Scissors cuts paper! You lose.")
elif user == "scissors":
    if computer_action == "paper":
        print("Scissors cuts paper! You win!")
    else:
        print("Rock smashes scissors! You lose.")