# -*- coding: utf-8 -*-
"""word frequency.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MkbfruVdhGkYCZaIB8ZVngUD8MJ1hRja
"""

input_string = input("Enter the input string: ")

def find_highest_frequency_word_length(input_string):
    words = input_string.split()
    word_frequency = {}

    for word in words:
        word_frequency[word] = word_frequency.get(word, 0) + 1

    if not word_frequency:
        return 0

    highest_frequency = max(word_frequency.values())
    highest_frequency_words = [word for word, freq in word_frequency.items() if freq == highest_frequency]
    highest_frequency_word_length = len(max(highest_frequency_words, key=len))

    return highest_frequency_word_length

highest_frequency_word_length = find_highest_frequency_word_length(input_string)
print("Length of the highest-frequency word:", highest_frequency_word_length)

